FROM postgres:16-alpine3.23

ENV POSTGRES_USER=${POSTGRES_USER} \
    POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
    POSTGRES_DB=du_portal_diploma

COPY postgres/du_portal_diploma.dump /docker-entrypoint-initdb.d/du_portal_diploma.dump
COPY init-restore.sh /docker-entrypoint-initdb.d/init-restore.sh
RUN chmod +x /docker-entrypoint-initdb.d/init-restore.sh

EXPOSE 5432